services:
  postgres:
    image: postgres:17

    container_name: orion-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: orion
      POSTGRES_PASSWORD: orion
      POSTGRES_DB: orion

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: